# Blowfish Menu Configuration
# https://blowfish.page/docs/getting-started/#menus

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 1

[[main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 2

[[main]]
  identifier = "categories"
  name = "Categories"
  url = "/categories/"
  weight = 3

[[main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 4
