# Blowfish Theme Parameters
# https://blowfish.page/docs/configuration/

# Color scheme
colorScheme = "blowfish"

# Appearance settings
defaultAppearance = "light"
autoSwitchAppearance = true

# Enable search
enableSearch = true

# Date format
dateFormat = "2006-01-02"

# Main sections (where blog posts are)
mainSections = ["posts"]

# Author configuration
[author]
  name = ""
  image = ""
  headline = ""
  bio = ""
  links = []

# Homepage configuration
[homepage]
  layout = "page"
  homepageImage = ""
  showRecent = true
  showRecentItems = 10
  showMoreLink = true
  showMoreLinkDest = "/posts"
  cardView = false
  cardViewScreenWidth = false
  layoutBackgroundBlur = false

# Article configuration
[article]
  showDate = true
  showViews = false
  showLikes = false
  showDateOnlyInArticle = false
  showDateUpdated = true
  showAuthor = true
  showAuthorBottom = false
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3
  showTaxonomies = true
  showAuthorsBadges = false
  showWordCount = false
  sharingLinks = ["twitter", "linkedin", "reddit", "email"]
  showZenMode = false

# List configuration
[list]
  showHero = false
  heroStyle = "background"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = false
  showSummary = true
  showViews = false
  showLikes = false
  showTableOfContents = true
  showCards = false
  orderByWeight = false
  groupByYear = true
  cardView = false
  cardViewScreenWidth = false

# Taxonomy configuration
[taxonomy]
  showTermCount = true
  showHero = false
  heroStyle = "background"
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = false
  cardView = false

# Term configuration
[term]
  showHero = false
  heroStyle = "background"
  showBreadcrumbs = false
  showViews = false
  showLikes = false
  showTableOfContents = true
  groupByYear = false
  cardView = false
  cardViewScreenWidth = false

# Header configuration
[header]
  layout = "basic"
  logo = ""
  logoDark = ""
  showTitle = true

# Footer configuration
[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true
